### ISSUE TITLE
Não consigo executar.

### ISSUE THREAD

**Issue by rregorr** [caputchinefrobles/doufinder#4]
Olá, Bruno. Viu seu projeto doufinder e, como trabalho em um órgão do judiciário federal e preciso fazer pesquisas diárias, gostaria de usá-lo/contribuir. Seria interessante que os termos de pesquisas pudessem ser inseridos já na interface inicial, e não no arquivo de texto. Fica a dica. abs

**Comment by rregorr** [comment]
> Olá, Bruno. O código executa, faz a procura no diario e, quando finaliza, da essa msg:
ERRO AO ENVIAR LOG: SMTP AUTH extension not supported by server.
Defini a configuração do main.py assim(gmail). :
def main(argv):
    config_smtp_servidor = 'smtp.google.com'
    config_smtp_porta = '587'
    config_smtp_usuario = 'meuUser'
    config_smtp_senha = 'MinhaSenha123'
    config_download_dir = ''
    flg_offline = False
    data_pesquisa = None

 **E do doufinder.cfg assim:**
[OFFLINE]
DOWNLOAD_DIR=

[EMAIL]
SMTP_REMETENTE=meuUser@gmail.com
SMTP_SERVIDOR=smtp.gmail.com
SMTP_PORTA=587
SMTP_USUARIO=meuUser@gmail.com
SMTP_SENHA=MinhaSenha123

[JORNAIS]
ID_JORNAL1=515
ID_JORNAL2=529
ID_JORNAL3=530
ID_EDICAO_EXTRA=

PAGINA_MIN=1
PAGINA_MAX=1100

**Comment by caputchinefrobles** [comment]
Olá @rregorr. Me desculpe a demora para responder.. estou trabalhando em um outro projeto e tinha um tempo que não entrava aqui. 

Então, a princípio, o script deve ser configurado usando SMTP interno da sua rede. 

Ele não foi testado para usar o SMTP do gmail, principalmente pq vc precisa autorizar, no seu Google Account, a permissão para o script logar com a sua senha (ver nas configurações de segurança da sua conta). 

Teste rodar o script apontando para um servidor SMTP local na rede do seu órgão, e veja se o erro ainda ocorre.

Obrigado pelo feedback.

**Comment by celiobraga** [comment]
Olá, boa tarde!
Eu consegui fazer todas as configurações, entretanto só faz a pesquisa por palavra chave na página 1
Seção 515, Página 1
https://pesquisa.in.gov.br/imprensa/servlet/INPDFViewer?jornal=515&pagina=1&data=07/10/2020&captchafield=firstAccess
Seção 529, Página 1
https://pesquisa.in.gov.br/imprensa/servlet/INPDFViewer?jornal=529&pagina=1&data=07/10/2020&captchafield=firstAccess
Seção 530, Página 1
https://pesquisa.in.gov.br/imprensa/servlet/INPDFViewer?jornal=530&pagina=1&data=07/10/2020&captchafield=firstAccess
Consegue me auxiliar por gentileza?

**Comment by caputchinefrobles** [comment]
> Olá, boa tarde!
> Eu consegui fazer todas as configurações, entretanto só faz a pesquisa por palavra chave na página 1
> Seção 515, Página 1
> https://pesquisa.in.gov.br/imprensa/servlet/INPDFViewer?jornal=515&pagina=1&data=07/10/2020&captchafield=firstAccess
> Seção 529, Página 1
> https://pesquisa.in.gov.br/imprensa/servlet/INPDFViewer?jornal=529&pagina=1&data=07/10/2020&captchafield=firstAccess
> Seção 530, Página 1
> https://pesquisa.in.gov.br/imprensa/servlet/INPDFViewer?jornal=530&pagina=1&data=07/10/2020&captchafield=firstAccess
> Consegue me auxiliar por gentileza?

Poderia incluir aqui o conteúdo da sessão [JORNAIS] do seu arquivo doufinder.cfg, a versão do python que vc está usando e qual a release do doufinder?

Obrigado

**Comment by celiobraga** [comment]
Bom dia Bruno!
Agradeço seu pronto retorno.

A versão do Python é 3.8.2  E o Release do doufinder é de 3 anos atrás. 

Este é o conteúdo do arquivo doufinder.cfg

[OFFLINE]
DOWNLOAD_DIR=

[EMAIL]
SMTP_REMETENTE=remetente@dominio.xyz
SMTP_SERVIDOR=servidor_smtp
SMTP_PORTA=25
SMTP_USUARIO=
SMTP_SENHA=

[JORNAIS]
ID_JORNAL1=515
ID_JORNAL2=529
ID_JORNAL3=530
ID_EDICAO_EXTRA=

PAGINA_MIN=1
PAGINA_MAX=1100


Agradeço imensamente sua ajuda.

**Comment by caputchinefrobles** [comment]
@celiobraga Vigi... atualiza para a release v1.0.3. 

Já tiveram mudanças no python mas principalmente mudanças na página do diario oficial. Recentemente a pagina do diario passou a apresentar os pdfs em https e quebrou o script. A release v1.0.3 já tem isso corrigido, mas vc precisa se atentar para isso aqui: https://github.com/caputchinefrobles/doufinder#erro-de-certificado

Não se esqueça de instalar também a dependência "certifi".

**Comment by celiobraga** [comment]
Muito obrigado por sua ajuda! vou configurar aqui.
Tenha um excelente dia!

**Comment by caputchinefrobles** [comment]
Ajustei para consulta via https feito.
